### ISSUE TITLE
statcast_season(year = 2024, dir = output_dir) issue

### ISSUE THREAD

**Issue by rbblyze** [beanumber/abdwr3edata#1]
output_dir <- getwd()  # You can specify a different directory if needed
> # Download Statcast data for the 2024 season
> statcast_season(year = 2024, dir = output_dir)
Retrieving data from 2024-03-20
trying URL 'https://baseballsavant.mlb.com/statcast_search/csv?all=true&hfPT=&hfAB=&hfBBT=&hfPR=&hfZ=&stadium=&hfBBL=&hfNewZones=&hfGT=R%7CPO%7CS%7C&hfC&hfSea=2024%7C&hfSit=&hfOuts=&opponent=&pitcher_throws=&batter_stands=&hfSA=&player_type=batter&hfInfield=&team=&position=&hfOutfield=&hfRO=&home_road=&game_date_gt=2024-03-20&game_date_lt=2024-03-20&hfFlag=&hfPull=&metric_1=&hfInn=&min_pitches=0&min_results=0&group_by=name&sort_col=pitches&player_event_sort=h_launch_speed&sort_order=desc&min_abs=0&type=details'
Content type 'application/download; charset=utf-8' length 1234252 bytes (1.2 MB)
downloaded 1.2 MB

Error in `map()`:
ℹ In index: 1.
Caused by error:
! Can't assign 92 names to a 94-column data.table
Run `rlang::last_trace()` to see where the error occurred.
> rlang::last_trace()
<error/purrr_error_indexed>
Error in `map()`:
ℹ In index: 1.
Caused by error:
! Can't assign 92 names to a 94-column data.table

I had the above error when I tried to use statcast_season for 2024.  Am I doing something wrong?

**Comment by bayesball** [comment]
There were changes to Statcast recently so it returns 94 variables instead
of 92.  The baseballr package has been revised to adjust for this.  I would
suggest reinstalling baseballr from the Github site:

devtools::install_github(repo = "BillPetti/baseballr")

Jim
[image: Bowling Green State University] Jim Albert
Emeritus Professor,
Mathematics and Statistics
Bowling Green State University
***@***.***

**Comment by beanumber** [comment]
Indeed, this is a known issue with `baseballr` (and not something we can fix):

https://github.com/BillPetti/baseballr/issues/340

**Comment by rbblyze** [comment]
Thanks for your reply, I will update the package.  I really enjoy the book
and the R package, thanks again!

Mike
